import { Student } from '../types';

export const SAMPLE_STUDENTS: Student[] = [
  { id: 'std_1', seatNumber: '01', name: '陳建宇', active: true },
  { id: 'std_2', seatNumber: '02', name: '林子晴', active: true },
  { id: 'std_3', seatNumber: '03', name: '黃冠宇', active: true },
  { id: 'std_4', seatNumber: '04', name: '張雅筑', active: true },
  { id: 'std_5', seatNumber: '05', name: '李承翰', active: true },
  { id: 'std_6', seatNumber: '06', name: '王品涵', active: true },
  { id: 'std_7', seatNumber: '07', name: '吳柏毅', active: true },
  { id: 'std_8', seatNumber: '08', name: '劉又嘉', active: true },
  { id: 'std_9', seatNumber: '09', name: '蔡睿哲', active: true },
  { id: 'std_10', seatNumber: '10', name: '楊詩婷', active: true },
  { id: 'std_11', seatNumber: '11', name: '許庭瑋', active: true },
  { id: 'std_12', seatNumber: '12', name: '鄭宇晨', active: true },
  { id: 'std_13', seatNumber: '13', name: '謝沛珊', active: true },
  { id: 'std_14', seatNumber: '14', name: '洪浩翔', active: true },
  { id: 'std_15', seatNumber: '15', name: '郭思妤', active: true },
  { id: 'std_16', seatNumber: '16', name: '曾宥廷', active: true },
  { id: 'std_17', seatNumber: '17', name: '邱禹諾', active: true },
  { id: 'std_18', seatNumber: '18', name: '廖芷萱', active: true },
  { id: 'std_19', seatNumber: '19', name: '賴敬堯', active: true },
  { id: 'std_20', seatNumber: '20', name: '徐若菱', active: true },
  { id: 'std_21', seatNumber: '21', name: '周楷傑', active: true },
  { id: 'std_22', seatNumber: '22', name: '葉佳蓉', active: true },
  { id: 'std_23', seatNumber: '23', name: '蘇俊穎', active: true },
  { id: 'std_24', seatNumber: '24', name: '莊詠晴', active: true },
];

export const GROUP_COLOR_PALETTES = [
  {
    bg: 'bg-emerald-50/80',
    border: 'border-emerald-200',
    badge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    accent: 'text-emerald-700',
    text: 'text-emerald-950',
    chip: 'bg-white text-emerald-900 border-emerald-200 hover:border-emerald-400',
  },
  {
    bg: 'bg-sky-50/80',
    border: 'border-sky-200',
    badge: 'bg-sky-100 text-sky-800 border-sky-300',
    accent: 'text-sky-700',
    text: 'text-sky-950',
    chip: 'bg-white text-sky-900 border-sky-200 hover:border-sky-400',
  },
  {
    bg: 'bg-amber-50/80',
    border: 'border-amber-200',
    badge: 'bg-amber-100 text-amber-800 border-amber-300',
    accent: 'text-amber-700',
    text: 'text-amber-950',
    chip: 'bg-white text-amber-900 border-amber-200 hover:border-amber-400',
  },
  {
    bg: 'bg-indigo-50/80',
    border: 'border-indigo-200',
    badge: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    accent: 'text-indigo-700',
    text: 'text-indigo-950',
    chip: 'bg-white text-indigo-900 border-indigo-200 hover:border-indigo-400',
  },
  {
    bg: 'bg-rose-50/80',
    border: 'border-rose-200',
    badge: 'bg-rose-100 text-rose-800 border-rose-300',
    accent: 'text-rose-700',
    text: 'text-rose-950',
    chip: 'bg-white text-rose-900 border-rose-200 hover:border-rose-400',
  },
  {
    bg: 'bg-violet-50/80',
    border: 'border-violet-200',
    badge: 'bg-violet-100 text-violet-800 border-violet-300',
    accent: 'text-violet-700',
    text: 'text-violet-950',
    chip: 'bg-white text-violet-900 border-violet-200 hover:border-violet-400',
  },
  {
    bg: 'bg-teal-50/80',
    border: 'border-teal-200',
    badge: 'bg-teal-100 text-teal-800 border-teal-300',
    accent: 'text-teal-700',
    text: 'text-teal-950',
    chip: 'bg-white text-teal-900 border-teal-200 hover:border-teal-400',
  },
  {
    bg: 'bg-orange-50/80',
    border: 'border-orange-200',
    badge: 'bg-orange-100 text-orange-800 border-orange-300',
    accent: 'text-orange-700',
    text: 'text-orange-950',
    chip: 'bg-white text-orange-900 border-orange-200 hover:border-orange-400',
  },
];
